org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError --enable-native-access=ALL-UNNAMED
android.useAndroidX=true
# This newDsl flag was added by the Flutter template
android.newDsl=false
# This builtInKotlin flag was added by the Flutter template
android.builtInKotlin=false

# If your system Java is newer than Java 17 (for example Java 26),
# Android Gradle tasks may fail (jlink errors). Install JDK 17 and
# uncomment and set the path below to force Gradle to use it.
# Example (Windows):
# Point Gradle to the installed Temurin JDK 17 so Android build uses Java 17
org.gradle.java.home=C:\\Program Files\\Eclipse Adoptium\\jdk-17.0.20.8-hotspot
